export const ACTIONS = {
    CHANGE_NAV_BAR: 'CHANGE_NAV_BAR',
    SET_SELECTED_ARTICLE: 'SET_SELECTED_ARTICLE',
    SET_SEARCH_KEY: 'SET_SEARCH_KEY',
    SET_PAGE: 'SET_PAGE',
    SET_SELECTED_SOURCES: 'SET_SELECTED_SOURCES',
    SET_SELECTED_COUNTRIES: 'SET_SELECTED_COUNTRIES',
    SET_START_DATE: 'SET_START_DATE',
    SET_END_DATE: 'SET_END_DATE'
};